### PR TITLE
Fixed orientation, #574

### PR DESCRIPTION
**Pull request by aronnebrivio**
Removed "orientation":"portrait" from manifest.webapp in order to follow device orientation (useful for tablets)

### CODE REVIEW

**Comment by TitanNano** [comment]
wouldn't it be better to set it to just change it to the device primary orientation? I think it's just "primary" or something.

**Comment by aronnebrivio** [comment]
I've tested with a tablet and with primary doesn't seem to work..

**Comment by TitanNano** [comment]
yes I'm sorry, just checked it. there is no primary value. My mistake.

**Comment by autonome** [comment]
@crdlc who can review and merge this?

**Pull request closed without merging**
