### PR TITLE
Add Japanese (ja) l10n

### PR DESCRIPTION
**Pull request by kyoshino**

### CODE REVIEW

**Comment by kyoshino** [comment]
I guess the current locale resource is at https://github.com/mozilla/loop-client-l10n and I'm already working on it. https://github.com/mozilla/loop-client-l10n/tree/master/l10n/ja

**Comment by flodolo** [comment]
They're two completely different things.

This is the app you install on the phone, loop-client-l10n is the website displayed when you join a call.

**Comment by kyoshino** [comment]
Thanks @flodolo, then I'm restoring the branch. Not sure people are seeing pull requests though.

**Comment by kyoshino** [comment]
This is no longer required.

**Pull request closed without merging**
